<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Mesto\Custom\Block\Products\BestSellerProducts
 */
?>
<?php
$_productCollection = $block->getProductCollection(); 
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
	$viewMode = 'grid';
	$image = 'category_page_grid';
	$showDescription = false;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$pos = $block->getPositioned();
?>

<div class="best-seller-product-block block-products-list <?php echo $viewMode; ?>">
	<?php // Display Block Title ?>
	<?php if($block->getBlockTitle()): ?>
		<h2 class="bestseller-product-title"><?php echo $block->getBlockTitle(); ?></h2>
	<?php endif; ?>
	<?php // Display Block Description ?>
	<?php if($block->getDescription()): ?>
		<p class="info"><?php echo $block->getDescription(); ?></p>
	<?php endif; ?>
</div>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
		<div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div>
	</div>
<?php else: ?>
    <div class="bestseller-product products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items"> 
			<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
			<?php foreach ($_productCollection as $_product): ?>
				<?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
				<div class="product-item-info" data-container="product-grid">
					<?php
					$productImage = $block->getImage($_product, $image);
					if ($pos != null) {
						$position = ' style="left:' . $productImage->getWidth() . 'px;'
							. 'top:' . $productImage->getHeight() . 'px;"';
					}
					?>
					<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
						<?= $productImage->toHtml() ?>
					</a>
					
					
					<div class="product details product-item-details">
						<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
						?>
						<strong class="product name product-item-name">
							<a class="product-item-link"
							   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
								<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
							</a>
						</strong>
					

						<?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
						<?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
						<?= $block->getProductDetailsHtml($_product) ?>

	
						<div class="product-item-inner">
							<div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
								<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
									<?php if ($_product->isSaleable()): ?>
										<?php $postParams = $block->getAddToCartPostParams($_product); ?>
										<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
											<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
											<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
											<?= $block->getBlockHtml('formkey') ?>
											<button type="submit"
													title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
													class="action tocart primary">
												<span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
											</button>
										</form>
									<?php else: ?>
										<?php if ($_product->isAvailable()): ?>
											<div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
										<?php else: ?>
											<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
										<?php endif; ?>
									<?php endif; ?>
								</div>

								
								<div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
										<a href="#" class="action towishlist"
											title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
												<span><?php echo __('Add to Wish List') ?></span>
										</a>
									<?php endif; ?>

									<?php if ($compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare')): ?>
										<a href="#"
											class="action tocompare"
											title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
											role="button">
												<span><?php echo __('Add to Compare') ?></span>
										</a>
									<?php endif; ?>
								</div>
							</div>


							<?php $showDescription = true; ?>
							<?php if ($showDescription):?>
								<div class="product description product-item-description">
									<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
									<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
									   class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
								</div>
							<?php endif; ?>
						</div>
					</div>
				</div>
				<?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
			<?php endforeach; ?>
        </ol>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>